// This code is automatically generated by the framework
const deleteExample = require('../../routes/deleteExample')
const getExample = require('../../routes/getExample')
const postExample = require('../../routes/postExample')

module.exports = [deleteExample,getExample,postExample]